# Generated by Django 3.1.2 on 2020-10-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20201015_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
