# Generated by Django 3.1.2 on 2020-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
