# Generated by Django 3.1.2 on 2020-10-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0005_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.CharField(blank=True, max_length=40, null=True)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_csv', to='files.files')),
                ('videos', models.ManyToManyField(related_name='videos_campaign', to='files.Videos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
