# Generated by Django 3.1.2 on 2020-10-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_videos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csv_file', verbose_name=''),
        ),
    ]
