# Generated by Django 3.1.2 on 2020-10-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_files'),
        ('create_videos_api', '0002_auto_20201017_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='csv_file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_csv', to='files.files'),
            preserve_default=False,
        ),
    ]
