import json


def load_data(config):

        config["text_lines"][0]["x"] = "10"
        config["text_lines"][0]["y"] = "20"
        config["text_lines"][0]["h_align"] = "center"
        config["text_lines"][0]["start_time"] = 0
        config["text_lines"][0]["end_time"] = 15
        config["text_lines"][0]["font"] = "projects/hiro/assets/Rye-Regular.ttf"
        config["text_lines"][0]["font_size"] = "20"
        config["text_lines"][0]["font_color"] = "#0FFFF0"
        config["text_lines"][0]["angle"] = "0"
        config["data_file"] = "feed.csv"
        config["adwords"]["ad"]["Destination Url"] = "ad"
        config["video_description"] = "Generated by Vogon."
        config["video"]= "cowboy_base_video.mp4"
        config["images"][0]["x"] = "20"
        config["images"][0]["y"] = "100"
        config["images"][0]["start_time"] = 1
        config["images"][0]["end_time"] = 10
        config["images"][0]["angle"] = 0
        config["images"][0]["h_align"] = "center"
        config["images"][0]["width"] = 100

        save(config)



def load_file():
    with open("config.json", "r") as read_file:
        config = json.load(read_file)
        read_file.close()
        load_data(config)

def save(config):
    with open("config.json", "w") as read_file:
        json.dump(config, read_file, indent=4)
        read_file.close()

if __name__ == '__main__': 
    load_file()




